### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by FedorSharapov** [Dimonix-mw/OtusHomeWork23#1]
Здравствуйте! Здорово, что попробовали mongoDB!

При параллельной загрузки в БД, мне кажется можно обойтись без Barrier и использовать только AutoResetEvent.

А еще кстати можно сделать настройку типа файла и реализовать паттерн фабрики для парсера типа `GeneratorFactory`. И в таком случае можно выбирать тип файла через настройки)

А вы пробовали для 3 000 000 записей в mongoDB? и возникали ли у вас ошибки из-за параллельного сохранения частей данных?

Я использвале SQLite и там возникали ошибки, а при использовании postgres нет!

**Comment by Dimonix-mw** [comment]
Здравствуйте, да, можно было обойтись и без Barrier, задача стояла попробовать как можно больше примитивов синхронизации использовать, поэтому использовал два. Идея про фабрики очень хорошая. Пробовал для разного количества записей, проблем не возникало.

**Comment by FedorSharapov** [comment]
https://github.com/Dimonix-mw/OtusHomeWork23/blob/6595adadc2d39b8853e7346e220ed595b2d5f4ec/Otus.Teaching.Concurrency.Import.Loader/Extensions.cs#L8-L14 Интересное решение!    
    
   
https://github.com/Dimonix-mw/OtusHomeWork23/blob/6595adadc2d39b8853e7346e220ed595b2d5f4ec/Otus.Teaching.Concurrency.Import.Loader/Program.cs#L58 Но в случае, если `customers.Count` будет нечетное(например 10005), тогда в результате мы получим на одну часть коллекции больше. Т.е. 2501, 2501, 2501, 2501, 1. И тогда у нас будет использоваться на один поток больше, чем задал пользователь.


У меня получилось следующим образом:
```
public static IEnumerable<IEnumerable<T>> Chunks<T>(this IEnumerable<T> source, int numOfChunk)
{
    var numCustomersPerThread = source.Count() / numOfChunk;
    var remainderCustomers = source.Count() % numOfChunk;

    for (int i = 0; i < numOfChunk; i++)
    {
        var countCustomers = (i != numOfChunk - 1) ? numCustomersPerThread : numCustomersPerThread + remainderCustomers;
        yield return source.Skip(i* numCustomersPerThread).Take(countCustomers);
    }
}
```
И в таком случае результатом будет 2501, 2501, 2501, 2502.     
Но я не уверен что это более правильное решение...   
Что думаете по этому поводу?

**Comment by Dimonix-mw** [comment]
верно подмечено про нечетность кол-ва элементов, только в моем случае последняя коллекция с 1 элементом вообще не обработается) это даже не учитывал при разработке, основное внимание было направлено на использование примитивов синхронизации, а так конечно с точки зрения работы программы это будет недочет, который в моем случае можно будет исправить  либо внеся изменение в логику метода расширения Partition, например так:

public static List<List<T>> Partition<T>(this List<T> values, int parts)
        {
            int i = 0;
            var partition = from item in values
                            group item by i++ % parts into part
                            select part.ToList();
            return partition.ToList();
        }
, либо воспользоваться Ваши методом.
